export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_FAIL = 'AJAX_CALL_FAIL';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_TRENDING_SUCCESS = 'LOAD_TRENDING_SUCCESS';
